services:
  - type: web
    name: cards-of-factoria
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install flask flask-socketio eventlet pillow psycopg2-binary
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
